# Generated by Django 4.0.5 on 2022-11-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('secondname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('pass1', models.CharField(max_length=200)),
                ('pass2', models.CharField(max_length=200)),
            ],
        ),
    ]
